Codelist/variable subclass
IAMconsortium/nomenclature pull request #174
Opened 2022-08-30 14:28 UTC by luciecastella

Linked to #137 

Create a VariableCodeList subclass

2022-08-30 15:04 UTC, phackstock requested changes
Very solid start @luciecastella.
A few comments below. 
One more thing to take care of is to go into the `tests/` folder and look for any reference to `CodeList` that should now be `VariableCodeList`. E.g. https://github.com/luciecastella/nomenclature/blob/codelist/variable-subclass/tests/test_codelist.py#L13.
There might be some region specific changes we made to the `mapping` attribute of `CodeList` so if you want you can try and reduce the complexity of the type hint. Since we're going to change it so that CodeLists contain Code instances anyway this is probably overkill at this point.

2022-08-31 11:23 UTC, luciecastella commented on nomenclature/definition.py
> +            if dim == "variable":
(implementing it now so that I don't forget)

2022-09-01 11:21 UTC, phackstock approved these changes
Very nice, looks good from my side. 
There's a couple of things that will be cleaned up in the next few PRs but for this one I'd say we're good.

2022-09-01 11:37 UTC, danielhuppmann approved these changes
Looks nice, thanks @luciecastella!

2022-09-01 11:37 UTC, merged