Add `VariableCodeList.units` attribute and tests
IAMconsortium/nomenclature pull request #289
Opened 2023-11-07 13:46 UTC by danielhuppmann

I just ran into a situation where I wanted to get all units from a VariableCodeList, so this PR adds an attribute for that...

**Open question**: going back and forth between set and list seems to make the order arbitrary, but allowing "None" (for dimensionless variables) also preempts ordering easily. One could simply drop "None" from that list (given that it's *not* a unit) or we could always add it at the end or replace by "dimensionless" (this is what **pint** does)...

2023-11-08 14:04 UTC, phackstock requested changes
Looks good to me. 
Two small comments below.
Regarding your questions, I would replace `None` with "dimensionless". Also you could use a frozenset as the return value. This way you could ensure that the value are unique and ordered.

2023-11-08 14:46 UTC, danielhuppmann commented on nomenclature/codelist.py
> +        return list(unit_set)
Call me old-fashioned, but I have cast all return-objects in pyam (index dimensions, etc.) to lists for consistency...

2023-11-08 14:46 UTC, danielhuppmann commented on nomenclature/codelist.py
> +                for u in variable.unit:
Nice...

2023-11-08 14:49 UTC, danielhuppmann commented
> Regarding your questions, I would replace None with "dimensionless". 

On second thought, I would actually not follow **pint** (use the string `dimensionless`) but follow pyam (using an empty string). This is closer to what a user will find in the yaml files, and it also always comes first in the ordering...

2023-11-08 14:54 UTC, phackstock commented
> On second thought, I would actually not follow pint (use the string dimensionless) but follow pyam (using an empty string). This is closer to what a user will find in the yaml files, and it also always comes first in the ordering...

Sounds good as well. I agree with your point that it's more in line with closely reproducing what's the yaml files.

2023-11-09 08:46 UTC, phackstock approved these changes
Looks good to me.

2023-11-09 09:01 UTC, merged