Add CLI command to validate scenario data file from definitions
IAMconsortium/nomenclature pull request #419
Opened 2024-10-22 15:40 UTC by dc-almeida

Closes #404

2024-10-23 05:02 UTC, phackstock requested changes
Nice addition @dc-almeida (sorry for jumping in here with a review).
Couple of comments in line below.

2024-10-23 06:43 UTC, dc-almeida commented
Thanks for the hawk-eye as always!

2024-10-23 06:49 UTC, phackstock commented
> Thanks for the hawk-eye as always!

You're welcome, always easier to spot these things in other people's work :D

2024-10-23 07:30 UTC, phackstock approved these changes
Thanks for the quick changes @dc-almeida.
Good to be merged from my side, in principle.
However, as mentioned in #419, I think the name of the command might be misleading and I think it should include an option to specify the dimensions that should be validated.

2024-10-23 07:35 UTC, danielhuppmann commented on tests/data/cli/validate_scenarios/definitions/region/regions.yaml
> +- common:
Can you use an existing definitions-folder in the test-data? We're adding quite a lot of very similar items here and it's hard to keep an overview...

2024-10-23 07:37 UTC, danielhuppmann commented on nomenclature/cli.py
> +    checking it against defined codelist(s)
Try to keep the docstring such that the first line is really only one line, per numpydoc standards.
```suggestion
    """Validate a scenario file against the codelists of a project
```

2024-10-23 07:53 UTC, danielhuppmann approved these changes
Thank you!

2024-10-23 07:58 UTC, phackstock commented
Before we go ahead with the merge if I understood our discussion in #419 correctly, this PR is still missing a dimensions option so that you can specify which dimension you want to validate, correct @danielhuppmann?

2024-10-23 09:09 UTC, danielhuppmann commented
I have a suggestion: we merge as is, and then @dc-almeida does a follow-up PR adding the dimensions for this CLI, and also extending the tests for the `validate-scenario` and `validate-project` to make sure that all three cases work as expected:
- explicit `dimensions` argument (this is currently tested in `test_cli_custom_dimensions_runs()`)
- if not given, use `dimensions` argument set from `nomenclature.yaml` (not sure if this is tested)
- if also not given, check all available folders

2024-10-24 04:48 UTC, phackstock commented
Sounds good to me.

2024-10-29 09:46 UTC, merged