Add a test for unexpected failing of validation with multiple units
IAMconsortium/nomenclature pull request #442
Opened 2024-12-18 13:27 UTC by danielhuppmann

Closes #441

2024-12-18 13:52 UTC, danielhuppmann commented
No idea why there was no test and why the submissions started failing now...

Due to some (weirdly) failing test, I noticed that the check "illegal characters in common definitions" was actually now testing for characters that were sanitized out of common-definition - so I added a quickfix for that (using a character that appears there) on top of the unit-quickfix.

2024-12-19 11:15 UTC, phackstock requested changes
Two small changes, then good to be merged.
I'd also suggest to rename the PR because you're not just adding a test, you're fixing the multiple unit issue itself.

2024-12-19 11:15 UTC, phackstock commented on nomenclature/codelist.py
> +            and unit not in to_list(self.mapping[variable].unit)
The `to_list(self.mapping[variable].unit)` already exists as property `units` of `VariableCode`:
```suggestion
            and unit not in self.mapping[variable].units
```

2024-12-19 11:15 UTC, phackstock commented on nomenclature/codelist.py
> +from pyam.utils import is_list_like, write_sheet, pattern_match, to_list
```suggestion
from pyam.utils import is_list_like, write_sheet, pattern_match
```

2024-12-19 12:35 UTC, danielhuppmann commented
Thanks for the suggestion, implemented your changes.

2024-12-19 13:00 UTC, phackstock approved these changes
Thanks for implementing my suggestions, good to be merged.

2024-12-19 13:01 UTC, merged